### ISSUE TITLE
Unhandled exception thrown in the Schedule form

### ISSUE THREAD

**Issue by KennyGrovenburg** [CSC470-Alphatronics/CSC470-Alphatronics#9]
If an employee searches the schedule within two arbitrary dates and then selects an empty row and clicks the "View Participants" button, an unhandled Null Reference Exception is thrown. This should be fixed so that when a search returns zero clinics, the schedule either doesn't show any rows for them to choose from or (a more logical option) if they try to view the participants of an empty row, it shows a pop-up box stating "No Clinic Selected" or "Please select an existing clinic." or something along those lines.

**Comment by Syribi** [comment]
Added a try-catch block to avoid this.
